### ISSUE TITLE
PDO dll's not loading

### ISSUE THREAD

**Issue by meet-bhagdev** [Azure/msphpsql#85]
Hey,
i'm very happy about the new driver and thank you guys a lot for all your work. I prepared a new release of a web application locally. Therefor i downloaded the latest Xampp version with PHP 7 and hoped that the driver will give me the possibility to connect to the Sql-Server database... Unfortunatelly it didn't worked.

I copied the provided dll-files into the php extention folder
i changed the php.ini file...
If i restart the xampp server and have a look at the phpinfo page the pdo und sqlserver driver weren't shown there... So it seemed to be, that the dll aren't recognized... The same procedure runs for me with the older 5.6PHP version and the 5.6-dll files...
Is there a configuration mistake of myself or an error in the dll files?
Thank's for your help and response!
Have a nice day!
V

**Comment by meet-bhagdev** [comment]
@Der-V : Can you confirm if you are using the appropriate mapping of the DLLs - x86 PDO driver with x86 PHP and x64 PDO driver with x64 PHP? I followed your steps and was able to load the PDO driver and verify using phpinfo(). Screenshot below:
 
![image](https://cloud.githubusercontent.com/assets/11928821/14584558/789a73dc-041a-11e6-9185-b338d1cba7cd.png)

**Comment by Der-V** [comment]
Oh my god, that was stupid. It was my mistake.... i wanted to download the 64bit version, but only the 32bit version of php7 was available... but i still downloaded the 64bit version of your driver... so the driver wasn't recognized because it was the wrong one... 

I'm sorry for that stupid question and thank you a lot for all your work!!!!
Stay on fire with your passion for programming :)

**Comment by meet-bhagdev** [comment]
@Der-V : Glad it worked out! Happy to help if you have any other questions. I will close this issue. Feel free to reopen it if needed. 

Cheers,
Meet
